/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/download/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_runs__run_id__download__kind__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Stream */
        get: operations["run_stream_api_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile Dataset
         * @description Compute an on-demand statistical profile of a stored dataset.
         */
        get: operations["profile_dataset_api_datasets__dataset_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_dataset_api_datasets_post */
        Body_upload_dataset_api_datasets_post: {
            /** File */
            file: string;
        };
        /** CappedColumn */
        CappedColumn: {
            /** Col */
            col: string;
            /** Count */
            count: number;
        };
        /** ClassBalance */
        ClassBalance: {
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Pct */
            pct: number;
        };
        /** ClassCount */
        ClassCount: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** CleaningSummary */
        CleaningSummary: {
            /** Dropped Dupes */
            dropped_dupes: number;
            /** Dropped Cols */
            dropped_cols: string[];
            /** Capped Cols */
            capped_cols: components["schemas"]["CappedColumn"][];
            /** Impute Strategy */
            impute_strategy: {
                [key: string]: string;
            };
            /** Rows Before */
            rows_before: number;
            /** Rows After */
            rows_after: number;
        };
        /** ColumnInfo */
        ColumnInfo: {
            /** Name */
            name: string;
            /** Dtype */
            dtype: string;
            /** Nulls */
            nulls: number;
        };
        /** ColumnProfile */
        ColumnProfile: {
            /** Name */
            name: string;
            /** Dtype */
            dtype: string;
            /** Kind */
            kind: string;
            /** Nulls */
            nulls: number;
            /** Null Pct */
            null_pct: number;
            /** Unique */
            unique: number;
            /** Is Constant */
            is_constant: boolean;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Mean */
            mean?: number | null;
            /** Std */
            std?: number | null;
            /** Top */
            top?: string | null;
            /** Top Freq */
            top_freq?: number | null;
        };
        /** ConfusionMatrix */
        ConfusionMatrix: {
            /** Labels */
            labels: string[];
            /** Matrix */
            matrix: number[][];
        };
        /** Correlation */
        Correlation: {
            /** Labels */
            labels: string[];
            /** Matrix */
            matrix: number[][];
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Dataset Id */
            dataset_id: string;
            /** Target */
            target: string;
        };
        /** DatasetResponse */
        DatasetResponse: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** N Rows */
            n_rows: number;
            /** N Cols */
            n_cols: number;
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
            /** Preview */
            preview: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Evaluation
         * @description Chart-ready data for the best model, evaluated on the hold-out test set.
         */
        Evaluation: {
            confusion_matrix?: components["schemas"]["ConfusionMatrix"] | null;
            roc_curve?: components["schemas"]["RocCurve"] | null;
            /**
             * Class Distribution
             * @default []
             */
            class_distribution: components["schemas"]["ClassCount"][];
            /**
             * Pred Vs Actual
             * @default []
             */
            pred_vs_actual: components["schemas"]["PredPoint"][];
            /**
             * Residuals
             * @default []
             */
            residuals: components["schemas"]["ResidualPoint"][];
            correlation?: components["schemas"]["Correlation"] | null;
        };
        /** FeatureImportance */
        FeatureImportance: {
            /** Feature */
            feature: string;
            /** Importance */
            importance: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelResult */
        ModelResult: {
            /** Name */
            name: string;
            /** Key */
            key: string;
            /** Problem Type */
            problem_type: string;
            /** Primary Metric */
            primary_metric: string;
            /** Primary Score */
            primary_score: number;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Cv Mean */
            cv_mean: number;
            /** Cv Std */
            cv_std: number;
            /** Rank */
            rank: number;
            /** Is Best */
            is_best: boolean;
        };
        /** PredPoint */
        PredPoint: {
            /** Actual */
            actual: number;
            /** Predicted */
            predicted: number;
        };
        /** ProfileOverall */
        ProfileOverall: {
            /** N Rows */
            n_rows: number;
            /** N Cols */
            n_cols: number;
            /** Memory Bytes */
            memory_bytes: number;
            /** Duplicate Rows */
            duplicate_rows: number;
            /** Missing Cells */
            missing_cells: number;
            /** Missing Pct */
            missing_pct: number;
            /** Numeric Cols */
            numeric_cols: number;
            /** Categorical Cols */
            categorical_cols: number;
            /** Datetime Cols */
            datetime_cols: number;
            /** Constant Cols */
            constant_cols: number;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Id */
            id: string;
            overall: components["schemas"]["ProfileOverall"];
            /** Columns */
            columns: components["schemas"]["ColumnProfile"][];
            /** Correlation Labels */
            correlation_labels: string[];
            /** Correlation */
            correlation: number[][];
            /** Suggested Target */
            suggested_target: string;
            /** Suggested Task */
            suggested_task: string;
            /** Suggested Reason */
            suggested_reason: string;
            /** Class Balance */
            class_balance: components["schemas"]["ClassBalance"][];
        };
        /** ResidualPoint */
        ResidualPoint: {
            /** Predicted */
            predicted: number;
            /** Residual */
            residual: number;
        };
        /** RocCurve */
        RocCurve: {
            /** Fpr */
            fpr: number[];
            /** Tpr */
            tpr: number[];
            /** Auc */
            auc: number;
        };
        /** RunResponse */
        RunResponse: {
            /** Run Id */
            run_id: string;
        };
        /** RunResult */
        RunResult: {
            /** Run Id */
            run_id: string;
            /** Dataset Id */
            dataset_id: string;
            /** Target */
            target: string;
            /** Problem Type */
            problem_type: string;
            /** N Rows */
            n_rows: number;
            /** N Features */
            n_features: number;
            /** Primary Metric */
            primary_metric: string;
            /** Best Model */
            best_model: string;
            /** Models */
            models: components["schemas"]["ModelResult"][];
            /** Feature Importance */
            feature_importance: components["schemas"]["FeatureImportance"][];
            /** Insights */
            insights: string[];
            cleaning: components["schemas"]["CleaningSummary"];
            evaluation?: components["schemas"]["Evaluation"] | null;
            /** Artifacts */
            artifacts: {
                [key: string]: string;
            };
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_runs__run_id__download__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                kind: "model" | "predictions" | "report" | "cleaned" | "pdf";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stream_api_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_api_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_dataset_api_datasets__dataset_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
